### ISSUE TITLE
Backward mapping

### ISSUE THREAD

**Issue by dnesteryuk** [rom-rb/rom#128]
Now the mapping is used only to map data coming from a storage:

```ruby
  define(:users) do
    model User

    attribute :name, from: :username
  end
```

It works fine. But, when we restrict records we have to use non-mapped names of the fields:

```ruby
  rom.read.users.restrict(username: 'John').to_a
```

The same thing is about creating/updating data:

```ruby
  rom.commands.users.try {
    create(
      username: 'John'
    ) 
  }  
```

It will be good to provide some mechanism for backwards mapping. I understand that it is up to developers of adapters to define the restriction and CRUD functionality and it is perfectly fine, I guess it is right direction, but ROM can make it easier if it provides some standard DSL for backwards mapping, something like:

```ruby
  rom.mappers.users.backward_transform[tuple]
```

I achieved this functionality in my adapter by using this way:

```ruby
  fields_mapper = rom.mappers.users.mapper.transformer.args.first.args.first.dup
  fields_mapper = fields_mapper.invert

  transformation = Transproc(:map_hash, fields_mapper)
  tuple = transformation[tuple]
```

But, it isn't good way, it is more like a trick which may not work with a new version of Rom.

**Comment by solnic** [comment]
This will be tackled at some point but I must admit it's very very very low on my personal priority list. Happy to accept PRs of course. I don't have any concrete ideas wrt interfaces though.

In general I see it as an extension of the reader interface that would provide a way to translate incoming "query" object into a form that matches inverted mappings.

I should probably mention that I'd like to build a query extension for ROM that would help in building complex queries.

Please also notice that in ROM a recommended way of reading relations is through custom methods, so `rom.read(:users).by_name('Foo')` rather than `rom.relations.users.restrict(username: 'Foo')` which would eliminate or at least reduce the need of 'inverted mappings' for querying relations.

**Comment by solnic** [comment]
Oh and regarding commands - similar story, we may introduce an interface to help with that.

**Comment by solnic** [comment]
This issue was moved to rom-rb/rom-mapper#12
