### ISSUE TITLE
Confusing error when Mapper not registered

### ISSUE THREAD

**Issue by mcls** [rom-rb/rom#147]
I got a confusing error when I forgot to register a mapper:

```
ROM::Registry::ElementNotFoundError:
       :user_task_counts doesn't exist in ROM::ReaderRegistry registry
```

Took me a while to find it was the mapper that was missing.

I guess it should be raising the following one, but isn't for some reason? https://github.com/rom-rb/rom/blob/17c442543baa084a26d5cff50457489afcc7e19b/lib/rom/mapper_registry.rb#L11

**Comment by solnic** [comment]
Can you show me how you got this error?

**Comment by mcls** [comment]
On my rom-sql fork, remove the mapper here: https://github.com/mcls/rom-sql/blob/master/spec/integration/read_spec.rb#L83-L85

**Comment by solnic** [comment]
OK I will check it out, this is a bug

**Comment by solnic** [comment]
...so, this is actually the expected behavior, when there are no mappers, then there are no readers, because readers are build to access mappers. The trick is (and that part can be confusing), that you don't define readers, you define mappers that's why you probably expected an error related to mapper.

I'm not sure how to improve this to be honest. Readers are really handy and can be used to extend behavior of loaded relations. I guess it's a matter of documentation.

**Comment by solnic** [comment]
Reader is gone, so this is gone too.
