### ISSUE TITLE
Tutorial: how to run it?

### ISSUE THREAD

**Issue by muescha** [rom-rb/rom#151]
there is this line in tutorial http://rom-rb.org/tutorials/rails/getting-started/
`rails new rom-todo-app -JTS -m http://rom-rb.org/tutorials/code/rom-todo-app-template.rb`

but since i use bundler i dont like to install the rails gem outside of a `Gemfile`

How i can run this tutorial otherwise?

**Comment by aflatter** [comment]
This is not specific to ROM but to Rails - and it's [Getting Started guide](http://guides.rubyonrails.org/getting_started.html) requires `gem install rails`. I'm not sure why you want to work around that, maybe because your rubygems installation is wrecked or something, but you can probably create a Gemfile containing just:

```
$ $EDITOR Gemfile
$ cat Gemfile
source 'https://rubygems.org'
gem 'rails', '4.2.0'
$ bundle
$ bundle exec rails new rom-todo-app -JTS -m http://rom-rb.org/tutorials/code/rom-todo-app-template.rb
```

Then move `rom-todo-app` somewhere else and delete the current directory.
