### ISSUE TITLE
Unintuitive association behaviour

### ISSUE THREAD

**Issue by mjtko** [rom-rb/rom#153]
As discussed on Gitter ([here](https://gitter.im/rom-rb/chat?at=54dbb079253f88e25fe46214) and [here](https://gitter.im/rom-rb/chat?at=54dd1543f5e2f7d667a7b230)), I was a bit confused about how the mappers operate when trying to create an aggregate.  I've put together [an app](https://github.com/mjtko/rom-associations-issues-demo-app) which hopefully clarifies some of the things I was trying to do.

Specifically, my comments in the [relations/tasks.rb](https://github.com/mjtko/rom-associations-issues-demo-app/blob/master/app/relations/tasks.rb) file detail what I had to do to get an aggregate working.

Steps to run:

 * clone the repo
 * `bundle`
 * bin/rake db:setup
 * bin/rails c
 
I think the main problem is to do with the column prefixing (or not -- I didn't realise I had to prefix to begin with but once I had figured that out, other problems occurred such as gotchas with column aliasing).  Ideally, I'd like not to have to explicitly `select:` or use Sequel magic to alias things in my `association_join` calls.

**Comment by solnic** [comment]
There are two factors here that make it hard to build complex mappings:

- mappers and relations are disconnected, it means that a mapper expects correct data structure to be sent and relations must provide those data structure, *you* builds those data structures using query DSL provided by rom-sql relation. there's no declarative way to specify those structures, it's just based on building sql queries
- handling name clashes in columns is semi-manual - when you use `association_join` under the hood we use `graph` interface from sequel that automatically qualifies conflicting column names, it's actually pretty messy because some columns get prefixed, some not. Then you need to know what was prefixed and set up a mapper properly. It's pretty brittle and annoying.

To improve this we need to make those things happen automatically, somehow. For instance we could have an interface in `Relation` that joins with another relation and by default prefix everything. In the mapper we use a convention that if we're mapping an aggregate then all attributes are prefixed. This would require extending `Mapper` DSL with sql-specific bits.

I would imagine something like that to work:

``` ruby
class Tasks < ROM::Relation[:sql]
  def with_workers
    # this qualifies all tasks columns *and* worker columns, just as a convention to simplify things
    association_join(:workers)    
  end
end

class TaskMapper < ROM::Mapper[:sql]
  attribute :id
  attribute :title
end

# excuse the awful name
class TaskWithWorkersMapper < TaskMapper
  # this incantation would rewrite all attributes to be prefixed and then do `group :workers, prefix: :workers`
  association :workers
end
````

**Comment by solnic** [comment]
Just wanted to mention that with ROM 0.7.0 we have `combine` interface that issues multiple queries and allows simple mapping into aggregates w/o the need for prefixing columns etc.

I'm keeping this issue open though as using joins is also useful and I think ROM should make it as easy as possible.

**Comment by solnic** [comment]
This is now scheduled for 1.0.0 and should be included in one of the 0.x.0 upgrades prior 1.0.0 final

**Comment by solnic** [comment]
With [rom-repository](https://github.com/rom-rb/rom-repository) building aggregates is trivial; hence this is finally not an issue. Closing :boom:
