### ISSUE TITLE
Adding Filemaker adapter

### ISSUE THREAD

**Issue by ginjo** [rom-rb/rom#197]
I've been working on an adapter for Filemaker server, [rom-fmp](https://github.com/ginjo/rom-fmp), and I seem to be a bit stuck on what exactly is a rom dataset, what are its behaviors and responsibilities, and how does it interact with relations. I understand that a dataset should respond to `each` and `to_a`, but what is the "true nature" of a rom dataset? From what I can tell, a dataset is sometimes an object that points to a database table (or table-like resource). Sometimes its an array of hashes. And sometimes its both.

I've tried a number of variations on dataset objects, mostly based on the existing rom adapters. I can get the lint tests working, generate basic queries & responses, and map responses to models. But I can't seem to make chained lazy relations work. I frequently get an error like `undefined method 'call' for {:some_search=>"criteria"}:Hash`

On the filemaker side, I have a ruby object that represents a filemaker table. This table object has full CRUD functionality, including a fairly comprehensive set of read/query methods. The table object returns an array-like collection of record hashes but does not store this array.

Some of the adapter structures I've tried:
- Use the filemaker table object as the dataset, adding `to_a` and `each` (these perform a "find-all" type of query).
- Wrap the table object in a charlatan instance as the dataset.
- Wrap the table object in an enumerable "resource" object, and pass that to a charlatan instance as dataset.

With each of these, I've tried query caching with `to_a` and `each` being the trigger to perform the actual query. The caching works great for a single non-chained relation. But when I finally resolve a chained cached-query, only one component of the chain is performed.

I feel like I'm really close but am missing something big. Any pointers on where I'm going wrong or where to look for enlightenment would be most welcome. Thanks!
##

**Comment by solnic** [comment]
A dataset is an object that exposes "native" interface to access data. The only required interface is `#each` though but typically datasets provide quite powerful interfaces that a relation can use. There's a macro you can use to forward certain calls to the underlaying dataset and this will enable query chaining, ie:

``` ruby
class ROM::Rmp::Relation < ROM::Relation
  forward :some, :methods, :exposed, :by, :dataset
end
```

**Comment by ginjo** [comment]
Back from a long hiatus building & maintaining servers...

Thanks for the tips above. I've tried rebuilding the adapter a few times now, starting with the examples from the adapter guides. I can get simple calls to the database server working with those examples. However I had to add a layer of query storage & management to the dataset to have lazy chained relations. It works, but I feel like I may not have designed it in the most 'rom' kind of way.

I'm still kind of fuzzy on the expectations & requirements of relations & datasets, and what responsibilities are where. For example, are lazy chained relations supposed to be handled by existing rom features? Or is it the adapter's responsibility to provide that functionality? Or a little of both?

The guides are shaping up and have been really helpful, but I'd like to see more details on the various adapter classes & methods, their purpose & expectations, and how to construct them to take full advantage of rom.

BTW, 0.9.1 is working really well - thanks for all the hard work!

**Comment by nepalez** [comment]
@ginjo Working on cassandra and kafka adapters i used the following rules for gateway - (connection) - dataset - relation - command:

1. [Gateway](https://github.com/rom-rb/rom-kafka/blob/master/lib/rom/kafka/gateway.rb) (subclass of `ROM::Gateway`) is a:
- registry of datasets
- storage of settings (like hosts, port, login, password) that are necessary to access the data
It is mutable for adding datasets.

2. [Connection](https://github.com/rom-rb/rom-kafka/blob/master/lib/rom/kafka/connection.rb) is the wrapper around the external driver(s) that provides the access
- hides the specifics of external library from the rest of the adapter
- adopts APIs of gateway/dataset to the external driver
It is mutable because the connection can have an internal state storing the history of data access (like the current log offset of Kafka messages being read).

Depending on the concrete driver, you can use either the same connection for reading/writing etc., or several types (like in Kafka, where messages producer and consumer connect to server slightly different). The connection can be instantiated and stored either by gateway or dataset (I'll read about this later).

3. [Dataset](https://github.com/rom-rb/rom-kafka/blob/master/lib/rom/kafka/dataset.rb) - models the top level of the "database" structure. It can be table in SQL, topic in Kafka, table/columns_family in Cassandra etc.

For example, in Kafka data are organized into topics/partitions. Because it is the Kafka itself who decided what partition of the topic to store data to, I allow adapter to access the topic (w/o any partition) for writing. I model it with a dataset. From the other side, the consumer access data via concrete partition. I do this by setting default partition (0) and allow user to modify it via special method (`#from(number)`, or I could do this via `#where(partition: ?)`).

So, while Kafka dataset models the topic (for writing), it can be additionally tuned with `:partition` options to describe `topic + partition` (for reading).

In Cassandra it is done slightly different. Cassandra models data via `keyspace` and `table` (`columns_family`). Because the official docs recommend using keyspace for domain model, I model the whole keyspace with gateway. If the user need to access various keyspaces, it should instantiate multi-gateway adapter. Here dataset models the `table` (not the top level of Cassandra whole data structure, but the top layer inside the gateway `keyspace`).

Dataset does 3 things:
- writes data via some connection
- reads data via some connection *lazily*. (implementing the Enumerable interface around the connection with `#each` method defined).
- stores specific settings to provide reads/writes (that can be modified from relation/command)

Couple of words about lazy reading. Look at [how this is made in Kafka](https://github.com/rom-rb/rom-kafka/blob/master/lib/rom/kafka/dataset.rb#L101-L104). Two points here:
- driver fetches data from server by chunks of some length, but [connection](https://github.com/rom-rb/rom-kafka/blob/master/lib/rom/kafka/connection/consumer.rb#L86-L93) hides this from the dataset - it authomatically fetches the next chunk when it is required by the dataset
- connection still iterates via all the data, but the dataset `#each` allows to stop iteration when user sets some limit.

And the last bit of puzzle is about where to instantiate connections. Kafka is a good example, because here is two types of connections (in many other cases there is one): for consumer and producer. 

- Because producer connection is topic/partition agnostic, I [instantiate and store "writer's connection" immeadiately inside the gateway](https://github.com/rom-rb/rom-kafka/blob/master/lib/rom/kafka/gateway.rb#L120). Then this connection can be reused by all datasets. I think this is a standard way of dealing, when gateway not only stores settings for connection, but connects by itself.
- From the other hand, the consumer in Kafka is topic/partition/offset - dependent. That's why "reader's connection" [instantiates by the dataset](https://github.com/rom-rb/rom-kafka/blob/master/lib/rom/kafka/dataset.rb#L78). And every time, when relation [reloads the dataset with new options](https://github.com/rom-rb/rom-kafka/blob/master/lib/rom/kafka/dataset.rb#L87-L89), I need to reconnect. It is slower then writing, but is a pay for customization.

I won't write about relation and command - they are too simple, but will be happy to answer if you have any question about them.

**Comment by ginjo** [comment]
@nepalez, thanks for the detailed overview. I think my dataset structure is somewhat similar to yours but with differences in the details. I have tried some different variations on the relation-dataset-command interaction. They all work, more or less, but I'm not sure which one is the "right" way to structure it. Here are some questions I'm trying to answer.

* ROM::Commands::Abstract#execute states that it should return an Array. Why not return a Dataset or a ROM::Relation::Loaded? Those both seem to work well and give more upstream information. 

* The examples in the adapter guide suggest to pipe commands thru the relation.

````
class UsersRelation < ROM::Relation
  forward :update, :create, :delete, ...
end

class UpdateUsers < ROM::Commands::Update[:fmp]
  def execute(attributes={})
    relation.update(attributes)
  end
end
````
I thought we were supposed to be keeping write concerns separate from read concerns. What makes more sense to me is to send writes to the dataset directly from the command.

    class UpdateUsers < ROM::Commands::Update[:fmp]
      def execute(attributes={})
        relation.dataset.update(attributes)
      end
    end

Then we can add some sugar to the relation, allowing it to create commands on the fly.

    class UsersRelation < ROM::Relation
      def update
        Commands::Update.new(self)
      end
    end

Are any of these right or wrong, or are they all acceptable structures?

**Comment by solnic** [comment]
> ROM::Commands::Abstract#execute states that it should return an Array. Why not return a Dataset or a ROM::Relation::Loaded? Those both seem to work well and give more upstream information.

A simple array can easily work with all adapters, datasets may not, since they are specific to a given adapter and may not have the same behavior that would make them work with the pipeline. And `Relation::Loaded` could be used but feels like an overhead for cases where you just simply want to map returned data into something else. I might be missing some use cases though so it's definitely something to discuss further.

> I thought we were supposed to be keeping write concerns separate from read concerns.

Commands give a separate interface to handle writes but they use relations which provide basic CRUD interface (typically in most adapters). We don't have a strict separation here.

>  What makes more sense to me is to send writes to the dataset directly from the command.

Yes, typically that's the way to go. in `rom-sql` we do that. Keep in mind that relation is needed *at least* to provide restricted relation views. (ie `by_id` etc.).

> Then we can add some sugar to the relation, allowing it to create commands on the fly.

I don't like that to be honest. This would make relations know about commands, right now commands only know about specific relation interfaces and relations are injected, the coupling is very minimal and I'd prefer to keep it like that. And relations have no clue that commands exist.

**Comment by ginjo** [comment]
Super helpful comments @solnic, thanks!   So, here are some highlights, as I understand:

* Relations don't know about commands, but commands can know about relations, minimally.
* It is ok for a relation to have a method that writes data, thru the dataset & adapter.
* A command can use a relation method to write data, but it doesn't have to.
* A command will need a relation, at the very least, to specify what record(s) are operated on.

Maybe a silly question, but how is an Update command different from a relation#update method, as far as functionality and use cases go? Or are they just two different ways to update data?

With loaded relations, is there a preferred way to apply a command to them? My use case is that I have a relation with loaded data, and I want to update all records in the relation without having to reload the relation (to get record_id's).

**Comment by solnic** [comment]
> Maybe a silly question, but how is an Update command different from a relation#update method, as far as functionality and use cases go? Or are they just two different ways to update data?

`Relation#update` is dumb and simply sends input to the storage through its dataset interface. Command is more sophisticated, it can check if `count` matches with the `result` setting (`:one` or `:many`), it can use an input handler to coerce some values into special types (ie an array into pg-array in rom-sql) and maybe more, depending on the adapter.

> With loaded relations, is there a preferred way to apply a command to them? My use case is that I have a relation with loaded data, and I want to update all records in the relation without having to reload the relation (to get record_id's).

We didn't have a use case like that so far but a specific adapter could implement that, a loaded relation has a reference to its source relation so you have the pieces in place.

**Comment by nepalez** [comment]
@ginjo Concerning strict separation of relations and commands you can look at how this is done for Cassandra. I don't know if this is an ideal solution, but "it works".

Dataset provides all the methods [`#get`](https://github.com/rom-rb/rom-cassandra/blob/master/lib/rom/cassandra/dataset.rb#L70-L72), `#create`, `#update`, `#delete` (all 3 via [method missing](https://github.com/rom-rb/rom-cassandra/blob/master/lib/rom/cassandra/dataset.rb#L92-L94)), and [`#batch`](https://github.com/rom-rb/rom-cassandra/blob/master/lib/rom/cassandra/dataset.rb#L60-L62). Every method just returns a new dataset, carrying a corresponding lazy query (to be modified and executed later).

Relation stores its dataset argument as a [`@source` and then redefines `@dataset` by applying `#get` method](https://github.com/rom-rb/rom-cassandra/blob/master/lib/rom/cassandra/relation.rb#L36-L37). So all relation's methods are forwarded not to the source dataset, but to the dataset, restricted for reading only.

Just in the same way every command is initialized with pre-updated relation, [wrapped around resticted dataset](https://github.com/rom-rb/rom-cassandra/blob/master/lib/rom/cassandra/commands.rb#L21) (restriction is just applying the command-specific method, like `:create` for create command etc.).

This is one of possible solutions to provide stricter separation, than defining command's methods in a relation.

**Comment by ginjo** [comment]
Thanks @solnic & @nepalez... again, really helpful.

I have another related, but possibly tangential, question about models & persistence. Not sure if this is the best place to ask, so I think I'll move it over to gitter...
