### ISSUE TITLE
Including methods in relations via module is not working

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#244]
I'm not sure if this is a bug or not but I was expecting this to work.
```ruby
require 'rom'

setup = ROM.setup(:memory)

module SelectActive
  def active
    restrict { |row| row[:active] }
  end
end

setup.relation(:users) do
  include SelectActive
end

setup.commands(:users) do
  define(:create)
end
rom = setup.finalize


UserCommands = rom.command(:users)
UserCommands.create(name: 'Nisse', active: true)
UserCommands.create(name: 'Hannes', active: true)
UserCommands.create(name: 'Björn', active: false)

puts rom.relation(:users).active.to_a
```
Error:
```
rom/relation/lazy.rb:117:in `method_missing': undefined method `active' for #<ROM::Relation::Lazy:0x007ff6c99e7150> (NoMethodError)
```

**Comment by AMHOL** [comment]
This is due to the use of <a href="http://ruby-doc.org/core-2.2.2/Module.html#method-i-method_added" target="_blank">Module.method_added</a> to expose relation methods in <a href="https://github.com/rom-rb/rom/blob/master/lib/rom/relation/class_interface.rb#L71-L74" target="_blank">Relation</a>, and when you include a module it doesn't actually define the methods on the including class, it just adds the module to the hierarchy to search when methods are invoked.

You can work around this with something like:

```ruby
require 'rom'

setup = ROM.setup(:memory)

module RelationInterface
  def included(base)
    base.exposed_relations.merge(instance_methods)
  end
end

module SelectActive
  extend RelationInterface

  def active
    restrict { |row| row[:active] }
  end
end

setup.relation(:users) do
  include SelectActive
end

setup.commands(:users) do
  define(:create)
end
rom = setup.finalize


UserCommands = rom.command(:users)
UserCommands.create.call(name: 'Nisse', active: true)
UserCommands.create.call(name: 'Hannes', active: true)
UserCommands.create.call(name: 'Björn', active: false)

rom.relation(:users).active.to_a
  # => [{:name=>"Nisse", :active=>true}, {:name=>"Hannes", :active=>true}]
```

I'm all for :fire: all t3h h00ks myself, but granted, it either needs to be better documented or implemented differently, perhaps it would be good to have something like RelationInterface in ROM?

**Comment by solnic** [comment]
Yeah this will be addressed prior 1.0.0 for sure. I'm reluctant when it comes to hooks too although I have to say that it's a pretty neat trick in this case ;)

I guess having `RelationInterface` module ain't that bad huh?

**Comment by AMHOL** [comment]
Yeah, think the `RelationInterface`  makes it a little nicer, Githubs stupid editor won't let me edit the comment above for some reason (it blanks out the text box), but that should be `public_instance_methods` rather than `instance_methods`

**Comment by solnic** [comment]
This will work now starting from 0.9.0 as Lazy behavior was merged into Relation and adapter DSL is no longer hidden so we don't mess with `method_added` and `exposed_relations` is no longer needed.

One small caveat is that if you want `auto_curry` to work with methods included from a module you will have to manually call `auto_curry name_of_the_method`.
