### ISSUE TITLE
Mapper challenges

### ISSUE THREAD

**Issue by nepalez** [rom-rb/rom#257]
I recognized that I see now 3 problems/challenges with mappers, that should be postponed to 0.9.0 (or, maybe to `rom-mappers`)

1. Change the visitor's path

Now mapping visitor's path consists of 2 global phases. At first it preprocesses all nodes with `group`, `fold` and their inversions, including nested groups. Then it visits plain attributes with renaming, filtering etc.

The problem with this approach is that it severely limits nesting, even in simplest way (`group { group }`), not to mention zoo cases like `ungroup { group { fold  } }`. For example, this code doesn't work:

```ruby
group :contacts do
  attribute :address, from: :email
  attribute :type

  group emails: [:address]
end
```
while this one does:

```ruby
group :contacts do
  attribute :email
  attribute :type

  group emails: [:email]
end
```

The reason is the renaming of `:email` into `:attribute` is done after the second nesting, not before it. This makes manipulations with attributes restricted by the root and the first level of nesting.

Transformation from:
```ruby
[
  { name: "jane", email: "jane@doe.com", type: "job" },
  { name: "jane", email: "jane@job.com", type: "job" }
]
```
into
```ruby
[
  {
    name: "jane",
    contacts: [
      { type: "job", emails: [{ address: "jane@doe.com" }, { address: "jane@job.com" }] }
    ]
  }
]
```
can be done only by chaining two mappers, first of which will rename attributes, while the second one will do nested grouping with them.

What I propose is to change visiting strategy. I think, the visitor should do a sequence of the same steps locally at any node:

- work off compositions (yes, we could compose relation in a deep levels of nesting because why not to?)
- preprocess `group`, `ungroup`, `fold`, `unfold`
- process other plain attributes
- go to the header (a level deeper) recursively

2) I think, we should clear out `except` by using it with transproc `reject_keys`. This allows to filter keys at the root level, not only inside blocks.

For clearing out grouped attributes we could use another method (rename the current one to another private method `clear_attributes` and keep the `except` in DSL only).

3) I'd like to made `prefix` and `prefix_separator` to work inside block in... well... more respectable way, than it does now. It wasn't a planned feature, but why not? With this the mapper API would become more constistent.

**Comment by solnic** [comment]
This:

``` ruby
group :contacts do
  attribute :address, from: :email
  attribute :type

  group emails: [:address]
end
```

is a weird way of defining mapping, makes me think we should remove this syntax, because it's the same as:

``` ruby
group :contacts do
  attribute :type

  group :emails do
    attribute :address, from: :email
  end
end
```

In general if a nested transformation requires mapping individual keys then those should be defined within the block, not at the root level. If you want the mapper to move keys from root to a nested structure then this is how it should be expressed.

I agree that this should work more consistently **but** we should probably think how to simplify the interface rather than making our lives harder by changing code so that some edge cases are covered while maintaining more complex interface.

Nesting should work consistently in multiple levels, that's of course something which must be addressed, but if `group/wrap foo: [:bar]` causes headaches - let's *remove it*, and only use block syntax.

**Comment by nepalez** [comment]
Think, you're right about the DSL.

This task can be closed, because its 1st part not necessary, 2nd is done by #264 , the third one requires some refactoring, but doesn't worth discussion
