### ISSUE TITLE
Rails - Nested resource routes and forms

### ISSUE THREAD

**Issue by pnomolos** [rom-rb/rom#262]
I've run into difficulty when using a form for a nested resource, because it's the `Form` object itself defining `to_model`, rather than the object instance.  Of course, with nested resources this means that I will need to build a `Form` instance for every object that is used to generated a URL for the route, and that seems like a bit of a waste.  At the same time, I appreciate that you're trying to avoid the monolithic/maximalist approach that Rails has taken.  Wondering if there might be any suggestions or ideas on how to solve this?  Mine would be a simplistic base interface you can include that implements the necessary `ActiveModel` extensions, but wondering if there's a better way about this.

Edit: I'm working around this for now by also passing `url:`, but that's obviously less than ideal as well.

**Comment by solnic** [comment]
Can you show me some code examples?

**Comment by pnomolos** [comment]
```ruby
# product_options.controller.rb
def new
  render :new, locals: { product: product, option: NewProductOptionForm.build }
end
```

```haml
= form_for [:admin, product, option] do |f|
	= render 'form', form: f
```

Blows up with `undefined method 'to_model' for #<Product:0x007fe5584c7c10>`

**Comment by pnomolos** [comment]
I fully understand _why_ it's blowing up, I'm wondering what the best way to solve this "Railism" is going to be.

**Comment by solnic** [comment]
forms implement AM::Model interface so I'm lost right now

**Comment by pnomolos** [comment]
@solnic Only option is a Form, product is just an instance of my Product model (which is just a PORO).  I'm wondering if there is an easy way around this beyond creating an additional Form object for the product.

**Comment by cflipse** [comment]
Oh, I think I see what the problem is:

`form_for` calls `to_model` on each of the parameters in its sequence.   Ugh.

I'm rather doubtful that we want to forcefully interact with the polymorphic URL and form resolvers; that way lies a particular breed of Cthulhu madness.

My best suggestion would be to wrap your `product` in an AM presenter, to expose the naming and other expected bits.

Which is a problem, because all the naming stuff is _class_ based, so really, you have to wrangle something to replace this:

https://github.com/rails/rails/blob/bbe170c90e7cf5a59ef3de8e246e78f50416a4cc/activemodel/lib/active_model/naming.rb#L235-L242


It might be worth providing some kind of base poro presenter for handling this; I've done a thing like this once or twice.  I'll try to see what I can extract.

**Comment by pnomolos** [comment]
What if there was a `ROM::Rails::Namer` (for lack of a better descriptor) instance that all the AM nonsense got delegated to, with the instance passed in as well?  So `product.to_model` would return `rom_rails_namer.to_model(product)` ?

**Comment by vrish88** [comment]
All of this AM craziness is related to figuring out the model name and the url for the record. If you provide the `:url` and `:as` options you can pass a PORO right into `form_for`.

```ruby
form_for option, as: :option, url: admin_product_option_path #...
```

Going forward though, I don't know we could communicate that they can do this with POROs.

**Comment by pnomolos** [comment]
Oh I know (and that's ultimately what I did) - the problem is that some
gems people use are going to depend on the AMness and there won't be any
getting around these sorts of things :(

We definitely need a (hopefully not too large) HOWTO on just dealing with
Railsisms

**Comment by solnic** [comment]
If you want to use a PORO then it must respond to AM stuff, there's no way around that, we just need to live with this

**Comment by solnic** [comment]
This issue was moved to rom-rb/rom-rails#47
