### ISSUE TITLE
rom-rails reloading is broken by spring

### ISSUE THREAD

**Issue by yarmiganosca** [rom-rb/rom#275]
Console reloading breaks when spring is running.

**Comment by cflipse** [comment]
For context, so I'll remember:

on a freshly generated rails4 app, after generating relations and commands, if you fire up a rails console, `ROM.env.commands` will be empty after a `reload!`

Removing Spring restores expected behavior.  It's _probably_ something to do with spring naming, and load paths, or, _mumble_ ... I don't use spring, so hadn't tripped across this before.  We'll want to fix it, though, or rom appears broken out of the box.

**Comment by solnic** [comment]
I just tried, `reload!` worked for me. Can we trigger reload after running generators?

**Comment by cflipse** [comment]
Set about reproducing this locally.

I can get the bad behaviour, but it goes away _once you restart spring_

The problem is, like all things with `spring`, that you get completely confusing behaviour until you realize it's running, and kick it over, then all is fine.

Strangely, relations and mappers seem to work fine here.  I have to wonder if the problem here (other than "using spring") is down to the commands being in a namespace module, rather than in the flat global namespace, like all-else in a rails app

**Comment by cflipse** [comment]
forgot to leave further notes:

I've got a better idea where the problem is coming from, and it's tied in with the AS::Dependencies autoloading; I just need to figure out how to make sure everything gets registered in the right place.

It _only_ occurs if you start rails before creating a mapper, relation or command.  If one already exists, it'll make it into the autoloaders correctly.

**Comment by solnic** [comment]
This issue was moved to rom-rb/rom-rails#46
