### ISSUE TITLE
Deprecate `validator` in Command API

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#299]
My experience so far has been that `validator` in command is a neat feature but only when you use a single command and validation is trivial.

More typical scenarios include more complicated validation logic and combining commands. In such cases validator set on an individual command is not feasible as it doesn't allow you to gather all errors and return them to the client as validator raises so it stops processing and you end up with errors just from one command.

So, this leads me to thinking that removing validation concept from commands is a good idea.

Thoughts?

**Comment by gotar** [comment]
I use those validation everywhere. Very useful for me.

**Comment by solnic** [comment]
@gotar I would support it as a command plugin.

What do you say?

**Comment by gotar** [comment]
Then why not, fair enough.

**Comment by cflipse** [comment]
Yeah, I think they should be moved out of the command.

It's a bit too opaque and magical and, as solnic says, it leads to issues with chained commands, and to things like: https://github.com/rom-rb/rom-rails/issues/42

An interesting structure might be to be able to throw a validator in _front_ of a command chain?
```
  command =   rom.validation(:new_task).unscheduled_task >> rom.command(:user).find_or_create >> rom.command(:tasks).create
  command.call(input_data)
  # => returns with result
```

Trick is probably that validations will likely depend a lot on the existing data / state of a structure, that might not be in the update data, so that validation interface isn't _really_ that simple either. :/

**Comment by solnic** [comment]
@cflipse I want to experiment with validations that would play nice in rom-model :)

**Comment by solnic** [comment]
@cflipse been thinking about that validation pipelining, it actually makes a lot of sense, rather than having configuration layer for validators we use pipeline composition, it's more "idiomatic rom" (I love saying that lol) too.

Speaking of which, pipeline operator has been extracted into `dry-pipeline` gem. I was thinking about turning rom container into a generic container open for extensions. We could store validators there too. I also want to extend mappers to support `>>`.

**Comment by cflipse** [comment]
starting https://github.com/rom-rb/rom-model/pull/2; PR for commentary
