### ISSUE TITLE
`map_with` returns Hashes, not ROM::Structs

### ISSUE THREAD

**Issue by georgemillo** [rom-rb/rom#370]
I'm trying to figure out how to rename keys in a ROM repo (e.g. if the name of a DB column isn't the name you want to use in your business logic) and I got it working with a mapper and the script below. (This is a contrived example where I'm renaming `email` to `primary_email`.

```
require 'rom'
require 'rom-repository'
require 'rom-sql'

class PersonMapper < ROM::Mapper
  relation :people
  register_as :person_mapper

  attribute :primary_email, from: :email
end

rom = ROM.container(:sql, 'sqlite::memory') do |conf|
  conf.default.create_table(:people) do
    primary_key :id
    column :email, String, null: false
  end

  conf.relation(:people) do
    schema(infer: true)
  end

  conf.register_mapper PersonMapper
end

class PersonRepo < ROM::Repository[:people]
  commands :create

  def normal
    people.first
  end

  def renamed_keys
    people.map_with(:person_mapper).first
  end
end
```

`renamed_keys` renames the attribute like I want, but it returns a *hash*, whereas the `normal` method above returns a ROM::Struct:

```
repo = PersonRepo.new(rom)
repo.create(email: "hello@example.com")

repo.normal
# => ROM::Struct[Person], email: "hello@example.com"
repo.renamed_keys
# => {:id=>1, :primary_email=>"hello@example.com"}
```

It's still a Hash even if I use `as`:

```
require 'dry-struct'
require 'dry-types'

class Person < Dry::Struct
  attribute :primary_email, Dry::Types['string']
end

class PersonRepo < ROM::Repository[:people]
  commands :create

  def renamed_keys
    people.map_with(:person_mapper).as(Person).first
  end
end

repo = PersonRepo.new(rom)

repo.create(email: "hello@example.com")

repo.renamed_keys
# => {:id=>1, :primary_email=>"hello@example.com"}
# ^^^ nothing has changed
```

Am I doing it wrong, or is this a bug?

**Comment by georgemillo** [comment]
Over on gitter @solnic has informed me that there's a much simpler way to rename columns like this:

```
require 'rom'
require 'rom-repository'
require 'rom-sql'

rom = ROM.container(:sql, 'sqlite::memory') do |conf|
  conf.default.create_table(:people) do
    primary_key :id
    column :email, String, null: false
  end

  conf.relation(:people) do
    schema(infer: true)
  end
end

class PersonRepo < ROM::Repository[:people]
  commands :create

  def renamed_keys
    # note the triple underscore:
    people.select(:email___primary_email).first
  end
end

repo = PersonRepo.new(rom)
repo.create(email: "hello@example.com")

puts repo.renamed_keys.primary_email
# => "hello@example.com"
# yay!
```

But my question about whether it's correct for `map_with` to return a hash still stands ;)

**Comment by solnic** [comment]
using `map_with` (`as` is just an alias for that) discards auto-mapping in repositories, that's why this happens. We can probably fairly easily [tweak this](https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/relation_proxy.rb#L61-L68) so it respects providing a model class along with any previously set mappers.

There's a related issue https://github.com/rom-rb/rom-repository/issues/12 where I was opposed to this feature, but now I'm on the fence, maybe we should allow it.

**Comment by georgemillo** [comment]
Ohhhhh I didn't realise that `as` and `map_with` are the same thing. I'm not sure what you mean by auto-mapping though? Not sure what you mean by "setting `model`" either (in the rom-repo issue you linked to), I had a quick skim through the guides and couldn't see anything about a method with that name.

If you decide not to add the above as a new feature, can we modify the behaviour so 'invalid' code like my original example fails noisily? Would reduce confusion.

**Comment by solnic** [comment]
> I'm not sure what you mean by auto-mapping though

auto-mapping in repository is one of its main features, it means that when you use repositories, mappers are generated automatically for you. In example converting results from relation graphs are automatic, and you get back aggregates; or converting relation tuples into custom models via `as(MyModel)`

> Not sure what you mean by "setting model" either

Setting a model is a rom-mapper feature, it's just `class UserMapper < ROM::Mapper; model User; end`. This type of a mapper is created automatically for you under the hood when you use `as(User)` in repositories

> If you decide not to add the above as a new feature, can we modify the behaviour so 'invalid' code like my original example fails noisily? Would reduce confusion.

Yes, that's why the original issue I linked to is still open. I'd like to discuss this with more people though, I'm not sure what we actually want to do :)

**Comment by georgemillo** [comment]
Got it, thanks 👍

**Comment by georgemillo** [comment]
(My original questions are resolved so this issue can probably be closed since there's already an issue about the same-ish problem)
