### ISSUE TITLE
Add a lint test for adapters

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#81]
To make it easy for people to create adapters we should have some kind of a lint test that checks that the bare minimum interface is implemented and works correctly.

We could have a shared rspec test or some test-framework agnostic solution.

**Comment by elskwid** [comment]
[active_model/lint](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/lint.rb) is an example of one way to do this.

I don't know *how* it should be used since it would be best to support any test framework. Probably be nice to have a linter that is framework agnostic as @solnic mentioned and include a couple of ways to aid in testing with `rspec` and `minitest` for example. The key here is, we know it won't be a lot of code but it will increase an adapter developer's confidence that what they're building will be compatible, and I feel like that may encourage more adapters to be written.

**Comment by solnic** [comment]
@elskwid framework-agnostic would probably simply mean using test/unit. I think this is actually a high priority task. We need as many adapters as possible to prove that ROM's design isn't blocking anything and is flexible enough...

**Comment by elskwid** [comment]
From our conversation yesterday, I'd like to see this part _specification_ and part runnable spec. Basically, set it up so the comments/docs are like reading the specification for an adapter:

I'd recommend we follow [RFC 2119](http://tools.ietf.org/html/rfc2119) for requirement key words:

```ruby
# adapter MUST provide foo
# adapter SHOULD provide bar
# adapter MAY provide baz
# adapter MUST NOT do mollusk
# ...
```

For each requirement we should have a runnable piece of code. I agree that test/unit would be nice since it ships with Ruby.

**Comment by solnic** [comment]
I think I'm gonna get this started today but my t/u fu sucks. You have been warned ;)

**Comment by solnic** [comment]
@elskwid how do I approach this must/should/may/must not concept using minitest?

**Comment by solnic** [comment]
...I mean, must/must not are obvious but "may" and "should"??

**Comment by elskwid** [comment]
@solnic Off the top of my head: we would have tests for MUST and MUST NOT then if there are things that MAY and SHOULD be added this could be the configuration we discussed. For instance, an adapter MAY allow writing back to the underlying data store. Is there a test for when it can handle that? If so, then we somehow tell the tests that it's available for linking.

**Comment by solnic** [comment]
@elskwid ah gotcha, I forgot that we talked about this, geez. I'll add a way to configure the test case class

**Comment by solnic** [comment]
isn't it done already?
